name: AnalogToBi
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - arrow-cpp=14.0.2
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.12.2
  - certifi=2024.8.30
  - charset-normalizer=2.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.5
  - datasets=2.19.1
  - dill=0.3.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - git-lfs=3.7.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - huggingface_hub=0.23.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcurl=8.7.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnghttp2=1.57.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.13.5
  - libxslt=1.1.41
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - ngspice=36
  - ngspice-exe=36
  - ngspice-lib=36
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.18
  - orc=1.7.4
  - packaging=23.2
  - pandas=2.0.3
  - pcre=8.45
  - pillow=10.3.0
  - pip=24.0
  - pkg-config=0.29.2
  - pthread-stubs=0.4
  - pyarrow=14.0.2
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.10.3
  - requests=2.32.2
  - s2n=1.3.27
  - safetensors=0.4.5
  - scikit-learn=1.3.0
  - scipy=1.9.3
  - seaborn=0.13.2
  - setuptools=75.3.0
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.45.3
  - swig=4.0.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.14
  - tokenizers=0.15.1
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tqdm=4.66.4
  - transformers=4.37.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxaw=1.0.14
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxmu=1.1.3
  - xorg-libxpm=3.5.13
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - blosc2==2.0.0
      - cffi==1.17.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.11
      - fonttools==4.57.0
      - git-filter-repo==2.47.0
      - gspan-mining==0.2.3
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - msgpack==1.1.0
      - orca==1.8
      - ply==3.11
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pycparser==2.23
      - pyparsing==3.1.4
      - pyspice==1.5
      - tables==3.8.0
      - tiktoken==0.7.0
      - toolz==1.0.0
      - torch-geometric==2.6.1
